SELECT cal.*
FROM AP_CAL_MST cal,
(
SELECT KAI_CODE, CAL_BNK_KBN, MAX(CAL_DATE) CAL_DATE
FROM AP_CAL_MST
WHERE KAI_CODE = /*kaiCode*/
AND CAL_DATE <= /*calDate*/
AND CAL_BNK_KBN = 0
GROUP BY KAI_CODE, CAL_BNK_KBN
) cal2
WHERE cal.KAI_CODE = cal2.KAI_CODE
AND  cal.CAL_DATE = cal2.CAL_DATE
AND  cal.CAL_BNK_KBN = cal2.CAL_BNK_KBN
