SELECT AP.CBK_CBK_CODE,
 /*$tablespace*/ CONCAT(NVL(BNK.BNK_NAME_S,''), /*$tablespace*/ CONCAT(' ', NVL(BNK.BNK_STN_NAME_S,''))) CBK_NAME,
  AP.CBK_YKN_KBN,
  AP.CBK_YKN_NO
FROM AP_CBK_MST AP
LEFT OUTER JOIN BNK_MST BNK
ON BNK.BNK_CODE = AP.CBK_BNK_CODE
AND BNK.BNK_STN_CODE = AP.CBK_STN_CODE
WHERE AP.KAI_CODE = /*kaiCode*/
AND AP.CBK_CBK_CODE = /*cbkCode*/
/*IF cbkKbn == "1"*/
 AND AP.CBK_OUT_FB_KBN = '1'
/*END*/