SELECT BMN_MST.DEP_NAME_S
  FROM DPK_MST LEFT OUTER JOIN BMN_MST
ON BMN_MST.KAI_CODE = DPK_MST.KAI_CODE
AND BMN_MST.DEP_CODE = DPK_MST.DPK_DEP_CODE
WHERE DPK_MST.KAI_CODE = /*kaiCode*/
  AND DPK_MST.DPK_SSK = /*dpkSsk*/
  AND DPK_MST.DPK_LVL = /*level*/
  AND DPK_MST.DPK_DEP_CODE = /*depCode*/
ORDER BY DPK_MST.DPK_DEP_CODE