SELECT DISTINCT
  a.DPK_SSK,
  a.DPK_LVL_0,
  b.KAI_NAME_S,
  a.KAI_CODE
FROM
  EVK_MST  a
LEFT JOIN
  ENV_MST  b
ON a.DPK_LVL_0 = b.KAI_CODE
WHERE 
  a.KAI_CODE = /*KAI_CODE*/
ORDER BY DPK_SSK