SELECT 
  D.KAI_CODE KAI_CODE,
  D.STR_DATE STR_DATE,
  D.END_DATE END_DATE,
  D.KAI_NAME_S KAI_NAME_s
FROM
ENV_MST D,
(SELECT DISTINCT
  a.KAI_CODE AKAI_CODE,
  b.DPK_DEP_CODE BKAI_CODE,
  a.KAI_NAME_s AKAI_NAME_s
FROM
  ENV_MST a
LEFT JOIN
  (SELECT 
		DPK_DEP_CODE
	FROM	EVK_MST
	WHERE	KAI_CODE	= /*KAI_CODE*/
    AND		DPK_SSK		= /*DPK_SSK*/) b
ON
    a.KAI_CODE = b.DPK_DEP_CODE) C
WHERE C.BKAI_CODE IS NULL
  AND D.KAI_CODE = C.AKAI_CODE
ORDER BY D.KAI_CODE
