SELECT DISTINCT
  a.KAI_CODE KAI_CODE,
  a.DPK_SSK DPK_SSK,
  a.DPK_DEP_CODE DPK_DEP_CODE,
  a.DPK_LVL DPK_LVL,
  CASE WHEN a.DPK_LVL_0 IS NULL THEN ' ' ELSE  a.DPK_LVL_0 END DPK_LVL_0,
  CASE WHEN a.DPK_LVL_1 IS NULL THEN ' ' ELSE  a.DPK_LVL_1 END DPK_LVL_1,
  CASE WHEN a.DPK_LVL_2 IS NULL THEN ' ' ELSE  a.DPK_LVL_2 END DPK_LVL_2,
  CASE WHEN a.DPK_LVL_3 IS NULL THEN ' ' ELSE  a.DPK_LVL_3 END DPK_LVL_3,
  CASE WHEN a.DPK_LVL_4 IS NULL THEN ' ' ELSE  a.DPK_LVL_4 END DPK_LVL_4,
  CASE WHEN a.DPK_LVL_5 IS NULL THEN ' ' ELSE  a.DPK_LVL_5 END DPK_LVL_5,
  CASE WHEN a.DPK_LVL_6 IS NULL THEN ' ' ELSE  a.DPK_LVL_6 END DPK_LVL_6,
  CASE WHEN a.DPK_LVL_7 IS NULL THEN ' ' ELSE  a.DPK_LVL_7 END DPK_LVL_7,
  CASE WHEN a.DPK_LVL_8 IS NULL THEN ' ' ELSE  a.DPK_LVL_8 END DPK_LVL_8,
  CASE WHEN a.DPK_LVL_9 IS NULL THEN ' ' ELSE  a.DPK_LVL_9 END DPK_LVL_9,
  a.STR_DATE STR_DATE,
  a.END_DATE END_DATE,
  b.KAI_NAME_s KAI_NAME_s
FROM
  EVK_MST  a
LEFT JOIN
  ENV_MST  b
ON a.DPK_DEP_CODE = b.KAI_CODE
WHERE 
  a.KAI_CODE = /*KAI_CODE*/
  AND a.DPK_SSK = /*DPK_SSK*/
ORDER BY DPK_LVL_0,
    DPK_LVL_1,
    DPK_LVL_2,
    DPK_LVL_3,
    DPK_LVL_4,
    DPK_LVL_5,
    DPK_LVL_6,
    DPK_LVL_7,
    DPK_LVL_8,
    DPK_LVL_9