SELECT KAI_CODE,KAI_NAME_S
FROM ENV_MST 
/*BEGIN*/WHERE
/*IF KAI_CODE != "" */ KAI_CODE  /*$KAI_CODE*/ /*END*/ -- LIKE
/*IF KAI_NAME_S != "" */ AND KAI_NAME_S  /*$KAI_NAME_S*/ /*END*/ -- LIKE
/*END*/
ORDER BY KAI_CODE