UPDATE SWK_DTL 
SET SWK_AT_KMK_CODE = /*SWK_KMK_CODE*/,
    SWK_AT_HKM_CODE = /*SWK_HKM_CODE*/,
    SWK_AT_UKM_CODE = /*SWK_UKM_CODE*/,
    SWK_AT_DEP_CODE = /*SWK_DEP_CODE*/
WHERE	KAI_CODE = /*KAI_CODE*/
AND		SWK_DEN_NO = /*SWK_DEN_NO*/ 
/*IF SWK_DC_KBN == 0 */ AND SWK_DC_KBN = 0 /*END*/
/*IF SWK_DC_KBN == 1 */ AND SWK_DC_KBN = 1 /*END*/ 