SELECT * 
FROM SWK_DTL DTL
WHERE DTL.KAI_CODE = /*KAI_CODE*/ 
AND DTL.SWK_DEN_NO = /*SWK_DEN_NO*/ 
/*IF SWK_DC_KBN == 0 */ AND DTL.SWK_DC_KBN = 0 /*END*/
/*IF SWK_DC_KBN == 1 */ AND DTL.SWK_DC_KBN = 1 /*END*/
