SELECT SJ.*, TRI.TRI_NAME_S, MKT.MKT_NAME
  FROM TRI_SJ_MST SJ
  LEFT OUTER JOIN AP_MKT_MST MKT ON SJ.GS_MKT_CODE = MKT.MKT_CODE, TRI_MST TRI
 WHERE SJ.KAI_CODE = /*KAI_CODE*/
   AND SJ.KAI_CODE = TRI.KAI_CODE
   AND SJ.TRI_CODE = TRI.TRI_CODE
   AND SJ.TRI_CODE = /*TRI_CODE*/
   AND SJ.TJK_CODE = /*TRI_SJ_CODE*/