SELECT DISTINCT
	SJ.*,
	TRI.TRI_NAME_S,
	MKT.MKT_NAME
FROM 
	TRI_SJ_MST SJ 
	LEFT OUTER JOIN AP_MKT_MST MKT
	ON SJ.GS_MKT_CODE = MKT.MKT_CODE,
	TRI_MST TRI
WHERE 
	SJ.KAI_CODE=/*KAI_CODE*/
AND
	SJ.KAI_CODE = TRI.KAI_CODE
AND 
	SJ.TRI_CODE = TRI.TRI_CODE

/*IF TRI_CODE_FROM != null && TRI_CODE_FROM != "" */ AND SJ.TRI_CODE >= /*TRI_CODE_FROM*/ /*END*/
/*IF TRI_CODE_TO != null && TRI_CODE_TO != "" */ AND SJ.TRI_CODE <= /*TRI_CODE_TO*/ /*END*/

ORDER BY
	SJ.TRI_CODE,
	SJ.TJK_CODE
	