SELECT 
 TRI.SIHA_HOU_CODE
FROM 
	TRI_SJ_MST TRI, AP_HOH_MST HOH
WHERE TRI.KAI_CODE =/*strKaiCode*/
AND TRI.TRI_CODE = /*strTjkCode*/
AND TRI.TJK_CODE = /*minTriSjcode*/
AND HOH.KAI_CODE = TRI.KAI_CODE
AND TRI.SIHA_HOU_CODE = HOH.HOH_HOH_CODE 
AND HOH.HOH_SIH_KBN = '1'
