UPDATE KTK_MST SET
KAI_CODE = /*dto.KAI_CODE*/,
KTK_KAI_CODE = /*dto.KTK_KAI_CODE*/,
KTK_DEP_CODE = /*dto.KTK_DEP_CODE*/,
KTK_KMK_CODE = /*dto.KTK_KMK_CODE*/,
KTK_HKM_CODE = /*dto.KTK_HKM_CODE*/,
KTK_UKM_CODE = /*dto.KTK_UKM_CODE*/,
INP_DATE = /*dto.INP_DATE*/,
UPD_DATE = /*dto.UPD_DATE*/,
PRG_ID = /*dto.PRG_ID*/,
USR_ID = /*dto.USR_ID*/,
KTK_TRI_CODE = /*dto.KTK_TRI_CODE*/
WHERE KAI_CODE = /*dto.KAI_CODE*/
AND KTK_KAI_CODE = /*dto.KTK_KAI_CODE*/
