UPDATE PRG_MST SET
KAI_CODE = /*dto.KAI_CODE*/,
SYS_CODE = /*dto.SYS_CODE*/,
PRG_CODE = /*dto.PRG_CODE*/,
PRG_NAME = /*dto.PRG_NAME*/,
PRG_NAME_S = /*dto.PRG_NAME_S*/,
PRG_NAME_K = /*dto.PRG_NAME_K*/,
KEN = /*dto.KEN*/,
COM = /*dto.COM*/,
LD_NAME = /*dto.LD_NAME*/,
STR_DATE = /*dto.STR_DATE*/,
END_DATE = /*dto.END_DATE*/,
INP_DATE = /*dto.INP_DATE*/,
UPD_DATE = /*dto.UPD_DATE*/,
PRG_ID = /*dto.PRG_ID*/,
USR_ID = /*dto.USR_ID*/,
PARENT_PRG_CODE = /*dto.PARENT_PRG_CODE*/,
MENU_KBN = /*dto.MENU_KBN*/,
DISP_INDEX = /*dto.DISP_INDEX*/
WHERE KAI_CODE = /*dto.KAI_CODE*/
AND SYS_CODE = /*dto.SYS_CODE*/
AND PRG_CODE = /*dto.PRG_CODE*/
