INSERT INTO USR_AUTH_MST (
KAI_CODE,
LOCK_OUT_ARR_CNT,
LOCK_OUT_RELEASE_TIME,
PWD_MIN_LENGTH,
PWD_TERM,
COMPLICATE_LVL,
HISTORY_MAX_CNT,
INP_DATE,
UPD_DATE,
PRG_ID,
USR_ID,
PWD_EXP_BEFORE_DAYS
) VALUES (
/*dto.KAI_CODE*/,
/*dto.LOCK_OUT_ARR_CNT*/,
/*dto.LOCK_OUT_RELEASE_TIME*/,
/*dto.PWD_MIN_LENGTH*/,
/*dto.PWD_TERM*/,
/*dto.COMPLICATE_LVL*/,
/*dto.HISTORY_MAX_CNT*/,
/*dto.INP_DATE*/,
/*dto.UPD_DATE*/,
/*dto.PRG_ID*/,
/*dto.USR_ID*/,
/*dto.PWD_EXP_BEFORE_DAYS*/
)