UPDATE USR_AUTH_MST SET
KAI_CODE = /*dto.KAI_CODE*/,
LOCK_OUT_ARR_CNT = /*dto.LOCK_OUT_ARR_CNT*/,
LOCK_OUT_RELEASE_TIME = /*dto.LOCK_OUT_RELEASE_TIME*/,
PWD_MIN_LENGTH = /*dto.PWD_MIN_LENGTH*/,
PWD_TERM = /*dto.PWD_TERM*/,
COMPLICATE_LVL = /*dto.COMPLICATE_LVL*/,
HISTORY_MAX_CNT = /*dto.HISTORY_MAX_CNT*/,
INP_DATE = /*dto.INP_DATE*/,
UPD_DATE = /*dto.UPD_DATE*/,
PRG_ID = /*dto.PRG_ID*/,
USR_ID = /*dto.USR_ID*/,
PWD_EXP_BEFORE_DAYS = /*dto.PWD_EXP_BEFORE_DAYS*/
WHERE KAI_CODE = /*dto.KAI_CODE*/
