package jp.co.ais.trans.master.ui;

import java.awt.event.*;

import jp.co.ais.trans2.define.*;

/**
 * 部門階層マスタ
 * 
 * @author liuchengcheng
 */
public class MG0050NewOrganizationDialog extends jp.co.ais.trans.common.gui.TDialog {

	private static final long serialVersionUID = 8942547956396766076L;

	protected MG0050NewOrganizationDialogCtrl ctrl;

	/**
	 * Creates new form MG0050NewOrganizationDialog
	 * 
	 * @param parent
	 * @param modal
	 * @param ctrl
	 */
	public MG0050NewOrganizationDialog(java.awt.Frame parent, boolean modal, MG0050NewOrganizationDialogCtrl ctrl) {
		super(parent, modal);
		initComponents();
		this.ctrl = ctrl;
		this.setResizable(false);

		// ** messageID変換, tab順登録のため、initComponents()の後に必ず呼ぶこと */
		super.initDialog();

		// fix bug: 確定ボタン押下して UI チェックが失敗の場合は、
		// ダイアログを閉じ時、dialog.isSettle = true;
		addWindowListener(new WindowAdapter() {

			public void windowClosing(WindowEvent ev) {
				btnReturn.doClick();
			}
		});
	}

	private boolean _isSettle = false;

	/**
	 * @return boolean
	 */
	public boolean isSettle() {
		return this._isSettle;
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
	 * content of this method is always regenerated by the Form Editor.
	 */

	protected void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		pnlButton = new jp.co.ais.trans.common.gui.TPanel();
		btnSettle = new jp.co.ais.trans2.common.gui.TImageButton(IconType.SETTLE);
		btnReturn = new jp.co.ais.trans.common.gui.TButton();
		pnlDetail = new jp.co.ais.trans.common.gui.TPanel();
		ctrlOrganizationCode = new jp.co.ais.trans.common.gui.TLabelField();
		ctrlLevel0 = new jp.co.ais.trans.common.gui.TButtonField();

		getContentPane().setLayout(new java.awt.GridBagLayout());

		setLangMessageID("C01698");
		pnlButton.setLayout(new java.awt.GridBagLayout());

		pnlButton.setMaximumSize(new java.awt.Dimension(520, 40));
		pnlButton.setMinimumSize(new java.awt.Dimension(520, 40));
		pnlButton.setPreferredSize(new java.awt.Dimension(520, 40));

		btnSettle.setTabControlNo(3);
		btnSettle.setLangMessageID("C01019");
		btnSettle.setShortcutKey(KeyEvent.VK_F9);
		btnSettle.setMaximumSize(new java.awt.Dimension(110, 25));
		btnSettle.setMinimumSize(new java.awt.Dimension(110, 25));
		btnSettle.setPreferredSize(new java.awt.Dimension(110, 25));
		btnSettle.addActionListener(new ActionListener() {

			public void actionPerformed(ActionEvent ev) {
				_isSettle = true;
				ctrl.disposeDialog();
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.insets = new java.awt.Insets(10, 240, 0, 0);
		pnlButton.add(btnSettle, gridBagConstraints);

		btnReturn.setLangMessageID("C01747");
		btnReturn.setShortcutKey(KeyEvent.VK_F12);
		btnReturn.setMaximumSize(new java.awt.Dimension(110, 25));
		btnReturn.setMinimumSize(new java.awt.Dimension(110, 25));
		btnReturn.setPreferredSize(new java.awt.Dimension(110, 25));
		btnReturn.setTabControlNo(4);
		btnReturn.setForClose(true);

		btnReturn.addActionListener(new ActionListener() {

			public void actionPerformed(ActionEvent ev) {
				_isSettle = false;
				ctrl.disposeDialog();
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 50);
		pnlButton.add(btnReturn, gridBagConstraints);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
		getContentPane().add(pnlButton, gridBagConstraints);

		pnlDetail.setLayout(new java.awt.GridBagLayout());

		pnlDetail.setMaximumSize(new java.awt.Dimension(660, 55));
		pnlDetail.setMinimumSize(new java.awt.Dimension(660, 55));
		pnlDetail.setPreferredSize(new java.awt.Dimension(660, 55));
		ctrlOrganizationCode.setMaxLength(5);
		ctrlOrganizationCode.setFieldSize(65);
		ctrlOrganizationCode.setLabelSize(60);
		ctrlOrganizationCode.setTabControlNo(1);
		ctrlOrganizationCode.setImeMode(false);
		ctrlOrganizationCode.setLangMessageID("C00335");
		ctrlOrganizationCode.getField().setAllowedSpace(false);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
		gridBagConstraints.insets = new java.awt.Insets(0, 25, 0, 0);
		pnlDetail.add(ctrlOrganizationCode, gridBagConstraints);

		ctrlLevel0.setMaxLength(10);
		ctrlLevel0.setButtonSize(85);
		ctrlLevel0.setFieldSize(120);
		ctrlLevel0.setLangMessageID("C00722");
		ctrlLevel0.setTabControlNo(2);
		ctrlLevel0.setImeMode(false);
		ctrlLevel0.setNoticeSize(410);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
		pnlDetail.add(ctrlLevel0, gridBagConstraints);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.insets = new java.awt.Insets(5, 0, 15, 0);
		getContentPane().add(pnlDetail, gridBagConstraints);

		pack();
	}

	jp.co.ais.trans.common.gui.TButton btnReturn;

	jp.co.ais.trans2.common.gui.TImageButton btnSettle;

	jp.co.ais.trans.common.gui.TButtonField ctrlLevel0;

	jp.co.ais.trans.common.gui.TLabelField ctrlOrganizationCode;

	jp.co.ais.trans.common.gui.TPanel pnlButton;

	jp.co.ais.trans.common.gui.TPanel pnlDetail;

}
