package jp.co.ais.trans.master.ui;

import java.awt.*;
import java.awt.event.*;
import java.beans.*;
import java.text.*;
import java.util.*;
import java.util.List;

import javax.swing.*;

import jp.co.ais.trans.common.gui.*;
import jp.co.ais.trans.common.log.*;
import jp.co.ais.trans.common.ui.*;
import jp.co.ais.trans.common.util.*;
import jp.co.ais.trans2.common.gui.*;
import jp.co.ais.trans2.define.*;

/**
 * カレンダーマスタ画面
 * 
 * @author yanwei
 */
public class MP0020CalendarMasterPanel extends TPanelBusiness {

	/** シリアルUID */
	private static final long serialVersionUID = 6975993877695662983L;

	/** 該当月の日数 */
	protected int intLastDay = 0;

	/** 何曜日 */
	protected int intDayOfWeek = 0;

	/** パネル */
	protected MP0020CalendarMasterPanelCtrl ctrl;

	private int j = 2;

	/** 確認ボタン押下可かどかチェック区分 */
	protected boolean settleFlg = true;

	/**
	 * コンストラクタ.
	 * 
	 * @param ctrl コントロールクラス
	 */
	MP0020CalendarMasterPanel(MP0020CalendarMasterPanelCtrl ctrl) {
		this.ctrl = ctrl;
		// 画面の初期化
		initComponents();
		// ** messageID変換, tab順登録のため、initComponents()の後に必ず呼ぶこと */
		super.initPanel();
		setSize(800, 600);
	}

	/**
	 * 画面の初期化
	 */
	public void setInit() {
		// 年の初期化
		int year = 1900;
		// 月の初期化
		int month = 1;
		// 日の初期化
		String strDate = "";
		// 該当日の初期化
		Date dtDate = new Date();
		// 該当日の取得
		strDate = (new SimpleDateFormat("yyyy/MM/dd")).format(dtDate);
		// 日付の設定
		txtObjectYears.setValue(dtDate);
		// 年の設定
		year = Integer.parseInt(strDate.substring(0, 4)); // year
		// 月の設定
		month = Integer.parseInt(strDate.substring(5, 7)); // month
		// データの取得
		FillData(year, month);
	}

	/**
	 * フレーム取得
	 */
	public Frame getParentFrame() {
		// フレームを返す
		return super.getParentFrame();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
	 * content of this method is always regenerated by the Form Editor.
	 */

	protected void initComponents() {
		GridBagConstraints gridBagConstraints;

		pnlBusiness = new TPanel();
		pnlButton = new TMainHeaderPanel();
		btnSettle = new TImageButton(IconType.SETTLE);
		btnSearch = new TImageButton(IconType.SEARCH);
		pnlHeader = new TPanel();
		lblEmployeePaymentDate = new TLabel();
		lblBankHoliday = new TLabel();
		lblTemporaryPaymentDate = new TLabel();

		txtObjectYears = new TPopupCalendar();
		txtObjectYears.setCalendarType(TPopupCalendar.TYPE_YM);
		lblSun = new TLabel();
		lblMon = new TLabel();
		lblTues = new TLabel();
		lblWed = new TLabel();
		lblThu = new TLabel();
		lblFri = new TLabel();
		lblSat = new TLabel();

		pnlFooter = new TPanel();

		for (int i = 0; i < 42; i++) {
			pnlDt[i] = new TPanel();
			pnlDt[i].setLayout(new GridBagLayout());
			pnlDt[i].setMaximumSize(new Dimension(100, 70));
			pnlDt[i].setMinimumSize(new Dimension(100, 70));
			pnlDt[i].setPreferredSize(new Dimension(100, 70));
			pnlDt[i].setBorder(BorderFactory.createLineBorder(Color.black));
		}
		pnlShow = new TPanel();

		for (int i = 0; i < 37; i++) {

			lbl[i] = new TLabel();
			lbl[i].setMaximumSize(new Dimension(25, 25));
			lbl[i].setMinimumSize(new Dimension(25, 25));
			lbl[i].setPreferredSize(new Dimension(25, 25));
			lbl[i].setFont(new Font("", 0, 20));
			chkEmp[i] = new TCheckBox();
			chkEmp[i].setLangMessageID("C02175");
			chkEmp[i].setMaximumSize(new Dimension(40, 14));
			chkEmp[i].setMinimumSize(new Dimension(40, 14));
			chkEmp[i].setPreferredSize(new Dimension(40, 14));
			chkEmp[i].setTabControlNo(j);

			chkBak[i] = new TCheckBox();
			chkBak[i].setLangMessageID("C02176");
			chkBak[i].setMaximumSize(new Dimension(40, 14));
			chkBak[i].setMinimumSize(new Dimension(40, 14));
			chkBak[i].setPreferredSize(new Dimension(40, 14));
			chkBak[i].setTabControlNo(j + 1);

			chkTep[i] = new TCheckBox();
			chkTep[i].setLangMessageID("C02177");
			chkTep[i].setMaximumSize(new Dimension(40, 14));
			chkTep[i].setMinimumSize(new Dimension(40, 14));
			chkTep[i].setPreferredSize(new Dimension(40, 14));
			chkTep[i].setTabControlNo(j + 2);

			j = j + 3;
		}

		setLayout(new GridBagLayout());
		setMaximumSize(new Dimension(800, 600));
		setMinimumSize(new Dimension(800, 600));
		setPreferredSize(new Dimension(800, 600));

		pnlBusiness.setLayout(new GridBagLayout());

		pnlBusiness.setMaximumSize(new Dimension(800, 600));
		pnlBusiness.setMinimumSize(new Dimension(800, 600));
		pnlBusiness.setPreferredSize(new Dimension(800, 600));

		pnlButton.setLayout(new GridBagLayout());

		pnlButton.setMaximumSize(new Dimension(800, 40));
		pnlButton.setMinimumSize(new Dimension(800, 40));
		pnlButton.setPreferredSize(new Dimension(800, 40));

		btnSettle.setLangMessageID("C01019");
		btnSettle.setShortcutKey(KeyEvent.VK_F9);
		btnSettle.setMaximumSize(new Dimension(110, 25));
		btnSettle.setMinimumSize(new Dimension(110, 25));
		btnSettle.setPreferredSize(new Dimension(110, 25));
		btnSettle.setTabControlNo(j + 2);
		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.anchor = GridBagConstraints.EAST;
		gridBagConstraints.insets = new Insets(10, 80, 5, 10);
		pnlButton.add(btnSettle, gridBagConstraints);
		btnSettle.addActionListener(new ActionListener() {

			public void actionPerformed(ActionEvent e) {
				btnSettleActionPerformed();
			}
		});

		btnSearch.setLangMessageID("C00155");
		btnSearch.setShortcutKey(KeyEvent.VK_F2);
		btnSearch.setMaximumSize(new Dimension(110, 25));
		btnSearch.setMinimumSize(new Dimension(110, 25));
		btnSearch.setPreferredSize(new Dimension(110, 25));
		btnSearch.setTabControlNo(j + 1);
		btnSearch.addActionListener(new ActionListener() {

			public void actionPerformed(ActionEvent e) {
				btnSearchActionPerformed();
				btnSettle.setEnabled(true);
			}
		});
		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		gridBagConstraints.insets = new Insets(10, 7, 5, 403);
		pnlButton.add(btnSearch, gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		gridBagConstraints.insets = new Insets(0, 0, 0, 0);
		gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
		pnlBusiness.add(pnlButton, gridBagConstraints);

		// 境界線
		JSeparator sep = new JSeparator();
		TGuiUtil.setComponentSize(sep, 0, 3);
		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridy = 1;
		gridBagConstraints.weightx = 1;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		gridBagConstraints.fill = GridBagConstraints.BOTH;
		pnlBusiness.add(sep, gridBagConstraints);

		pnlHeader.setLayout(new GridBagLayout());

		pnlHeader.setMaximumSize(new Dimension(800, 60));
		pnlHeader.setMinimumSize(new Dimension(800, 60));
		pnlHeader.setPreferredSize(new Dimension(800, 60));

		lblEmployeePaymentDate.setLangMessageID("C01115");
		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		gridBagConstraints.insets = new Insets(0, 0, 0, 0);
		pnlHeader.add(lblEmployeePaymentDate, gridBagConstraints);

		lblBankHoliday.setLangMessageID("C01044");
		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		gridBagConstraints.insets = new Insets(3, 0, 0, 0);
		pnlHeader.add(lblBankHoliday, gridBagConstraints);

		lblTemporaryPaymentDate.setLangMessageID("C01329");
		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		gridBagConstraints.insets = new Insets(3, 0, 0, 0);
		pnlHeader.add(lblTemporaryPaymentDate, gridBagConstraints);

		txtObjectYears.setMinimumSize(new Dimension(80, 20));
		txtObjectYears.setMinimumDate(DateUtil.getDate(1900, 01, 01));
		txtObjectYears.setMaximumDate(DateUtil.getDate(2099, 12, 31));
		txtObjectYears.setTabControlNo(1);
		txtObjectYears.setAllowableBlank(false);
		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.gridheight = 6;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		gridBagConstraints.insets = new Insets(0, 0, 0, 505);
		pnlHeader.add(txtObjectYears, gridBagConstraints);

		txtObjectYears.addPropertyChangeListener(new PropertyChangeListener() {

			public void propertyChange(PropertyChangeEvent ev) {
				if (ev.getPropertyName() == "value") {
					btnSettle.setEnabled(false);
				}
			}
		});

		txtObjectYears.setInputVerifier(new TInputVerifier() {

			public boolean verifyCommit(JComponent comp) {
				// チェックを行った
				if (settleFlg) {
					// 年月が変更の場合
					if (txtObjectYears.isValueChanged()) {
						btnSettle.setEnabled(false);
						settleFlg = false;
					} else {
						btnSettle.setEnabled(true);
					}
				}
				return true;
			}
		});

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		gridBagConstraints.insets = new Insets(0, 5, 0, 0);
		pnlBusiness.add(pnlHeader, gridBagConstraints);

		pnlShow.setLayout(new GridBagLayout());
		pnlShow.setMaximumSize(new Dimension(702, 452));
		pnlShow.setMinimumSize(new Dimension(702, 452));
		pnlShow.setPreferredSize(new Dimension(702, 452));

		// 日曜
		lblSun.setText(ctrl.getWord("C03519"));
		lblSun.setFont(new Font("", 0, 20));
		lblSun.setForeground(Color.red);
		lblSun.setHorizontalAlignment(SwingConstants.CENTER);
		lblSun.setMaximumSize(new Dimension(100, 30));
		lblSun.setMinimumSize(new Dimension(100, 30));
		lblSun.setPreferredSize(new Dimension(100, 30));
		lblSun.setBorder(BorderFactory.createLineBorder(Color.black));
		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		pnlShow.add(lblSun, gridBagConstraints);

		// 月曜
		lblMon.setText(ctrl.getWord("C01546"));
		lblMon.setFont(new Font("", 0, 20));
		lblMon.setHorizontalAlignment(SwingConstants.CENTER);
		lblMon.setMaximumSize(new Dimension(100, 30));
		lblMon.setMinimumSize(new Dimension(100, 30));
		lblMon.setPreferredSize(new Dimension(100, 30));
		lblMon.setBorder(BorderFactory.createLineBorder(Color.black));
		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		pnlShow.add(lblMon, gridBagConstraints);

		// 火曜
		lblTues.setText(ctrl.getWord("C01547"));
		lblTues.setFont(new Font("", 0, 20));
		lblTues.setHorizontalAlignment(SwingConstants.CENTER);
		lblTues.setMaximumSize(new Dimension(100, 30));
		lblTues.setMinimumSize(new Dimension(100, 30));
		lblTues.setPreferredSize(new Dimension(100, 30));
		lblTues.setBorder(BorderFactory.createLineBorder(Color.black));
		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 0;
		pnlShow.add(lblTues, gridBagConstraints);

		// 水曜
		lblWed.setText(ctrl.getWord("C01548"));
		lblWed.setFont(new Font("", 0, 20));
		lblWed.setHorizontalAlignment(SwingConstants.CENTER);
		lblWed.setMaximumSize(new Dimension(100, 30));
		lblWed.setMinimumSize(new Dimension(100, 30));
		lblWed.setPreferredSize(new Dimension(100, 30));
		lblWed.setBorder(BorderFactory.createLineBorder(Color.black));
		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 3;
		gridBagConstraints.gridy = 0;
		pnlShow.add(lblWed, gridBagConstraints);

		// 木曜
		lblThu.setText(ctrl.getWord("C01549"));
		lblThu.setFont(new Font("", 0, 20));
		lblThu.setHorizontalAlignment(SwingConstants.CENTER);
		lblThu.setMaximumSize(new Dimension(100, 30));
		lblThu.setMinimumSize(new Dimension(100, 30));
		lblThu.setPreferredSize(new Dimension(100, 30));
		lblThu.setBorder(BorderFactory.createLineBorder(Color.black));
		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 4;
		gridBagConstraints.gridy = 0;
		pnlShow.add(lblThu, gridBagConstraints);

		// 金曜
		lblFri.setText(ctrl.getWord("C01550"));
		lblFri.setFont(new Font("", 0, 20));
		lblFri.setHorizontalAlignment(SwingConstants.CENTER);
		lblFri.setMaximumSize(new Dimension(100, 30));
		lblFri.setMinimumSize(new Dimension(100, 30));
		lblFri.setPreferredSize(new Dimension(100, 30));
		lblFri.setBorder(BorderFactory.createLineBorder(Color.black));
		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 5;
		gridBagConstraints.gridy = 0;
		pnlShow.add(lblFri, gridBagConstraints);

		// 土曜
		lblSat.setText(ctrl.getWord("C01551"));
		lblSat.setFont(new Font("", 0, 20));
		lblSat.setHorizontalAlignment(SwingConstants.CENTER);
		lblSat.setForeground(Color.blue);
		lblSat.setMaximumSize(new Dimension(100, 30));
		lblSat.setMinimumSize(new Dimension(100, 30));
		lblSat.setPreferredSize(new Dimension(100, 30));
		lblSat.setBorder(BorderFactory.createLineBorder(Color.black));
		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 6;
		gridBagConstraints.gridy = 0;
		pnlShow.add(lblSat, gridBagConstraints);

		lbl[0].setForeground(Color.red);
		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.EAST;
		pnlDt[0].add(lbl[0], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[0].add(chkEmp[0], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[0].add(chkBak[0], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[0].add(chkTep[0], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		pnlShow.add(pnlDt[0], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.EAST;
		pnlDt[1].add(lbl[1], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[1].add(chkEmp[1], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[1].add(chkBak[1], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[1].add(chkTep[1], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		pnlShow.add(pnlDt[1], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.EAST;
		pnlDt[2].add(lbl[2], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[2].add(chkEmp[2], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[2].add(chkBak[2], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[2].add(chkTep[2], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 1;
		pnlShow.add(pnlDt[2], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.EAST;
		pnlDt[3].add(lbl[3], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[3].add(chkEmp[3], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[3].add(chkBak[3], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[3].add(chkTep[3], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 3;
		gridBagConstraints.gridy = 1;
		pnlShow.add(pnlDt[3], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.EAST;
		pnlDt[4].add(lbl[4], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[4].add(chkEmp[4], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[4].add(chkBak[4], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[4].add(chkTep[4], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 4;
		gridBagConstraints.gridy = 1;
		pnlShow.add(pnlDt[4], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.EAST;
		pnlDt[5].add(lbl[5], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[5].add(chkEmp[5], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[5].add(chkBak[5], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[5].add(chkTep[5], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 5;
		gridBagConstraints.gridy = 1;
		pnlShow.add(pnlDt[5], gridBagConstraints);

		lbl[6].setForeground(Color.blue);
		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.EAST;
		pnlDt[6].add(lbl[6], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[6].add(chkEmp[6], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[6].add(chkBak[6], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[6].add(chkTep[6], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 6;
		gridBagConstraints.gridy = 1;
		pnlShow.add(pnlDt[6], gridBagConstraints);

		lbl[7].setForeground(Color.red);
		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.EAST;
		pnlDt[7].add(lbl[7], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[7].add(chkEmp[7], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[7].add(chkBak[7], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[7].add(chkTep[7], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 2;
		pnlShow.add(pnlDt[7], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.EAST;
		pnlDt[8].add(lbl[8], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[8].add(chkEmp[8], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[8].add(chkBak[8], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[8].add(chkTep[8], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		pnlShow.add(pnlDt[8], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.EAST;
		pnlDt[9].add(lbl[9], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[9].add(chkEmp[9], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[9].add(chkBak[9], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[9].add(chkTep[9], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 2;
		pnlShow.add(pnlDt[9], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.EAST;
		pnlDt[10].add(lbl[10], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[10].add(chkEmp[10], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[10].add(chkBak[10], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[10].add(chkTep[10], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 3;
		gridBagConstraints.gridy = 2;
		pnlShow.add(pnlDt[10], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.EAST;
		pnlDt[11].add(lbl[11], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[11].add(chkEmp[11], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[11].add(chkBak[11], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[11].add(chkTep[11], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 4;
		gridBagConstraints.gridy = 2;
		pnlShow.add(pnlDt[11], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.EAST;
		pnlDt[12].add(lbl[12], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[12].add(chkEmp[12], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[12].add(chkBak[12], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[12].add(chkTep[12], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 5;
		gridBagConstraints.gridy = 2;
		pnlShow.add(pnlDt[12], gridBagConstraints);

		lbl[13].setForeground(Color.blue);
		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.EAST;
		pnlDt[13].add(lbl[13], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[13].add(chkEmp[13], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[13].add(chkBak[13], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[13].add(chkTep[13], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 6;
		gridBagConstraints.gridy = 2;
		pnlShow.add(pnlDt[13], gridBagConstraints);

		lbl[14].setForeground(Color.red);
		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.EAST;
		pnlDt[14].add(lbl[14], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[14].add(chkEmp[14], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[14].add(chkBak[14], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[14].add(chkTep[14], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 3;
		pnlShow.add(pnlDt[14], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.EAST;
		pnlDt[15].add(lbl[15], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[15].add(chkEmp[15], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[15].add(chkBak[15], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[15].add(chkTep[15], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 3;
		pnlShow.add(pnlDt[15], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.EAST;
		pnlDt[16].add(lbl[16], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[16].add(chkEmp[16], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[16].add(chkBak[16], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[16].add(chkTep[16], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 3;
		pnlShow.add(pnlDt[16], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.EAST;
		pnlDt[17].add(lbl[17], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[17].add(chkEmp[17], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[17].add(chkBak[17], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[17].add(chkTep[17], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 3;
		gridBagConstraints.gridy = 3;
		pnlShow.add(pnlDt[17], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.EAST;
		pnlDt[18].add(lbl[18], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[18].add(chkEmp[18], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[18].add(chkBak[18], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[18].add(chkTep[18], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 4;
		gridBagConstraints.gridy = 3;
		pnlShow.add(pnlDt[18], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.EAST;
		pnlDt[19].add(lbl[19], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[19].add(chkEmp[19], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[19].add(chkBak[19], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[19].add(chkTep[19], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 5;
		gridBagConstraints.gridy = 3;
		pnlShow.add(pnlDt[19], gridBagConstraints);

		lbl[20].setForeground(Color.blue);
		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.EAST;
		pnlDt[20].add(lbl[20], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[20].add(chkEmp[20], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[20].add(chkBak[20], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[20].add(chkTep[20], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 6;
		gridBagConstraints.gridy = 3;
		pnlShow.add(pnlDt[20], gridBagConstraints);

		lbl[21].setForeground(Color.red);
		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.EAST;
		pnlDt[21].add(lbl[21], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[21].add(chkEmp[21], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[21].add(chkBak[21], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[21].add(chkTep[21], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 4;
		pnlShow.add(pnlDt[21], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.EAST;
		pnlDt[22].add(lbl[22], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[22].add(chkEmp[22], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[22].add(chkBak[22], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[22].add(chkTep[22], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 4;
		pnlShow.add(pnlDt[22], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.EAST;
		pnlDt[23].add(lbl[23], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[23].add(chkEmp[23], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[23].add(chkBak[23], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[23].add(chkTep[23], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 4;
		pnlShow.add(pnlDt[23], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.EAST;
		pnlDt[24].add(lbl[24], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[24].add(chkEmp[24], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[24].add(chkBak[24], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[24].add(chkTep[24], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 3;
		gridBagConstraints.gridy = 4;
		pnlShow.add(pnlDt[24], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.EAST;
		pnlDt[25].add(lbl[25], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[25].add(chkEmp[25], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[25].add(chkBak[25], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[25].add(chkTep[25], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 4;
		gridBagConstraints.gridy = 4;
		pnlShow.add(pnlDt[25], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.EAST;
		pnlDt[26].add(lbl[26], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[26].add(chkEmp[26], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[26].add(chkBak[26], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[26].add(chkTep[26], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 5;
		gridBagConstraints.gridy = 4;
		pnlShow.add(pnlDt[26], gridBagConstraints);

		lbl[27].setForeground(Color.blue);
		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.EAST;
		pnlDt[27].add(lbl[27], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[27].add(chkEmp[27], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[27].add(chkBak[27], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[27].add(chkTep[27], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 6;
		gridBagConstraints.gridy = 4;
		pnlShow.add(pnlDt[27], gridBagConstraints);

		lbl[28].setForeground(Color.red);
		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.EAST;
		pnlDt[28].add(lbl[28], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[28].add(chkEmp[28], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[28].add(chkBak[28], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[28].add(chkTep[28], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 5;
		pnlShow.add(pnlDt[28], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.EAST;
		pnlDt[29].add(lbl[29], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[29].add(chkEmp[29], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[29].add(chkBak[29], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[29].add(chkTep[29], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 5;
		pnlShow.add(pnlDt[29], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.EAST;
		pnlDt[30].add(lbl[30], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[30].add(chkEmp[30], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[30].add(chkBak[30], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[30].add(chkTep[30], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 5;
		pnlShow.add(pnlDt[30], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.EAST;
		pnlDt[31].add(lbl[31], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[31].add(chkEmp[31], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[31].add(chkBak[31], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[31].add(chkTep[31], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 3;
		gridBagConstraints.gridy = 5;
		pnlShow.add(pnlDt[31], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.EAST;
		pnlDt[32].add(lbl[32], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[32].add(chkEmp[32], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[32].add(chkBak[32], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[32].add(chkTep[32], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 4;
		gridBagConstraints.gridy = 5;
		pnlShow.add(pnlDt[32], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.EAST;
		pnlDt[33].add(lbl[33], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[33].add(chkEmp[33], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[33].add(chkBak[33], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[33].add(chkTep[33], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 5;
		gridBagConstraints.gridy = 5;
		pnlShow.add(pnlDt[33], gridBagConstraints);

		lbl[34].setForeground(Color.blue);
		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.EAST;
		pnlDt[34].add(lbl[34], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[34].add(chkEmp[34], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[34].add(chkBak[34], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[34].add(chkTep[34], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 6;
		gridBagConstraints.gridy = 5;
		pnlShow.add(pnlDt[34], gridBagConstraints);

		lbl[35].setForeground(Color.red);
		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.EAST;
		pnlDt[35].add(lbl[35], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[35].add(chkEmp[35], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[35].add(chkBak[35], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[35].add(chkTep[35], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 6;
		pnlShow.add(pnlDt[35], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.EAST;
		pnlDt[36].add(lbl[36], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[36].add(chkEmp[36], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[36].add(chkBak[36], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		pnlDt[36].add(chkTep[36], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 6;
		pnlShow.add(pnlDt[36], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 6;
		pnlShow.add(pnlDt[37], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 3;
		gridBagConstraints.gridy = 6;
		pnlShow.add(pnlDt[38], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 4;
		gridBagConstraints.gridy = 6;
		pnlShow.add(pnlDt[39], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 5;
		gridBagConstraints.gridy = 6;
		pnlShow.add(pnlDt[40], gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 6;
		gridBagConstraints.gridy = 6;
		pnlShow.add(pnlDt[41], gridBagConstraints);

		pnlShow.setBorder(BorderFactory.createLineBorder(Color.black));
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 3;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		gridBagConstraints.insets = new Insets(0, 53, 0, 0);
		pnlBusiness.add(pnlShow, gridBagConstraints);

		pnlFooter.setLayout(new GridBagLayout());

		pnlFooter.setMaximumSize(new Dimension(800, 48));
		pnlFooter.setMinimumSize(new Dimension(800, 48));
		pnlFooter.setPreferredSize(new Dimension(800, 48));

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 4;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		gridBagConstraints.insets = new Insets(0, 0, 0, 0);
		gridBagConstraints.fill = GridBagConstraints.BOTH;
		gridBagConstraints.weightx = 1;
		gridBagConstraints.weighty = 1;
		pnlBusiness.add(pnlFooter, gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		gridBagConstraints.insets = new Insets(0, 0, 0, 0);
		gridBagConstraints.fill = GridBagConstraints.BOTH;
		gridBagConstraints.weightx = 1;
		gridBagConstraints.weighty = 1;
		add(pnlBusiness, gridBagConstraints);

	}

	TImageButton btnSearch;

	TImageButton btnSettle;

	TPopupCalendar dtObjectYears;

	TPopupCalendar txtObjectYears;

	TLabel lblBankHoliday;

	TLabel lblEmployeePaymentDate;

	TLabel lblTemporaryPaymentDate;

	TMainHeaderPanel pnlButton;

	TPanel pnlShow;

	TPanel pnlHeader;

	TPanel[] pnlDt = new TPanel[42];

	TLabel lblSun;

	TLabel lblMon;

	TLabel lblTues;

	TLabel lblWed;

	TLabel lblThu;

	TLabel lblFri;

	TLabel lblSat;

	TLabel[] lbl = new TLabel[37];

	TCheckBox[] chkEmp = new TCheckBox[37];

	TCheckBox[] chkBak = new TCheckBox[37];

	TCheckBox[] chkTep = new TCheckBox[37];

	TPanel pnlBusiness;

	TPanel pnlFooter;

	/**
	 * 検索ボタンの処理
	 */

	protected void btnSearchActionPerformed() {
		// 年の初期化
		int year = 1900;
		// 月の初期化
		int month = 1;
		// 日の初期化
		String strDate = "";
		// 日付の取得
		strDate = ctrl.chkDate(DateUtil.toYMDHMSString(txtObjectYears.getValue()));
		// 日付ではない場合
		if ("false".equals(strDate)) return;
		// 年の取得
		year = Integer.parseInt(strDate.substring(0, 4));
		// 月の取得
		month = Integer.parseInt(strDate.substring(5, 7));
		// データの取得
		this.FillData(year, month);

		settleFlg = true;
	}

	/**
	 * 確定ボタンの処理
	 */

	protected void btnSettleActionPerformed() {

		if (!ctrl.disposeDialog()) return;

		String strDate = "";
		// 日付の取得
		strDate = DateUtil.toYMDHMSString(txtObjectYears.getValue());
		strDate.substring(0, 7);
		// 日付の初期化
		String calDate = "";
		// 社員支払対象日の初期化
		String calHarai = "";
		// 銀行休業日の初期化
		String calBnkKbn = "";
		// 臨時支払対象日の初期化
		String calSha = "";
		// 日付の削除
		ctrl.delete(strDate, intLastDay);
		for (int i = 0; i < intLastDay; i++) {
			// 日付の設定
			calDate = strDate.substring(0, 7) + "/" + String.valueOf(i + 1);
			// データの処理

			// 社員支払対象日の設定
			calHarai = String.valueOf(BooleanUtil.toInt(chkEmp[i + intDayOfWeek].isSelected()));
			// 銀行休業日の設定
			calBnkKbn = String.valueOf(BooleanUtil.toInt(chkBak[i + intDayOfWeek].isSelected()));
			// 臨時支払対象日の設定
			calSha = String.valueOf(BooleanUtil.toInt(chkTep[i + intDayOfWeek].isSelected()));
			// データの登録
			ctrl.insert(calDate, calHarai, calBnkKbn, calSha);
		}
	}

	/**
	 * データの取得
	 * 
	 * @param year
	 * @param month
	 */
	public void FillData(int year, int month) {
		try {
			// 日付の初期化
			Calendar cal = Calendar.getInstance();
			// 年の設定
			cal.set(Calendar.YEAR, year);
			// 月の設定
			cal.set(Calendar.MONTH, month - 1);
			// 日の設定
			cal.set(Calendar.DATE, 1);
			// 日数の設定
			intLastDay = cal.getActualMaximum(Calendar.DATE);
			// 曜日の設定
			intDayOfWeek = cal.get(Calendar.DAY_OF_WEEK) - 1;
			// 日曜日の設定
			if (intDayOfWeek < 0) intDayOfWeek = 0;
			// 画面項目のクリア
			for (int i = 0; i < 37; i++) {
				// 日の表示
				lbl[i].setVisible(true);
				// 日のクリア
				lbl[i].setText("");
				// 社員支払対象日の表示
				chkEmp[i].setVisible(true);
				// 銀行休業日の表示
				chkBak[i].setVisible(true);
				// 臨時支払対象日の表示
				chkTep[i].setVisible(true);
				// 土日を判定
				boolean isHoliday = i == 0 || i == 6 || i == 7 || i == 13 || i == 14 || i == 20 || i == 21 || i == 27
					|| i == 28 || i == 34 || i == 35 ? true : false;

				// 社員支払対象日のクリア
				chkEmp[i].setSelected(false);
				// 銀行休業日のセット
				chkBak[i].setSelected(isHoliday);
				// 臨時支払対象日のクリア
				chkTep[i].setSelected(false);
			}
			// 画面項目の非表示
			for (int i = 0; i < intDayOfWeek; i++) {
				// 日の非表示
				lbl[i].setVisible(false);
				// 社員支払対象日の非表示
				chkEmp[i].setVisible(false);
				// 銀行休業日の非表示
				chkBak[i].setVisible(false);
				// 臨時支払対象日の非表示
				chkTep[i].setVisible(false);
			}
			// 画面項目の非表示
			for (int i = intLastDay + intDayOfWeek; i < 37; i++) {
				// 日の非表示
				lbl[i].setVisible(false);
				// 社員支払対象日の非表示
				chkEmp[i].setVisible(false);
				// 銀行休業日の非表示
				chkBak[i].setVisible(false);
				// 臨時支払対象日の非表示
				chkTep[i].setVisible(false);
			}
			// 日の表示
			for (int i = intDayOfWeek; i < intLastDay + intDayOfWeek; i++)
				// 日の表示
				lbl[i].setText(String.valueOf(i + 1 - intDayOfWeek));
			// 日付の設定
			cal.set(Calendar.DATE, 1);
			// 開始日の取得
			Date dteFrom = cal.getTime();
			// 日付の設定
			cal.set(Calendar.DATE, intLastDay);
			// 終了日の設定
			Date dteTo = cal.getTime();
			// 表示データの取得
			ctrl.reflesh(dteFrom, dteTo);
			// 確定ボタンの有効化

		} catch (Exception ex) {
			// 正常に処理されませんでした
			ClientLogger.error(this.getClass().getName(), ex);
		}
	}

	/**
	 * データの設定
	 * 
	 * @param lisRt
	 */
	public void setDte(List lisRt) {
		// 画面項目の設定
		for (int i = 0; i < lisRt.size(); i++) {
			// 該当データの取得
			List lisRow = (List) lisRt.get(i);
			// 日の取得
			int intCel = Integer.parseInt(((String) lisRow.get(1)).substring(8, 10));
			// 社員支払対象日の設定
			chkEmp[intCel + intDayOfWeek - 1].setSelected("1".equals(lisRow.get(2)));
			// 銀行休業日の設定
			chkBak[intCel + intDayOfWeek - 1].setSelected("1".equals(lisRow.get(3)));
			// 臨時支払対象日の設定
			chkTep[intCel + intDayOfWeek - 1].setSelected("1".equals(lisRow.get(4)));
		}
	}

}
