package jp.co.ais.trans.master.ui;

import java.awt.*;
import java.awt.event.*;

import javax.swing.*;

import com.klg.jclass.table.data.*;

import jp.co.ais.trans.common.gui.*;

/**
 * 会社階層マスタREFダイアログ
 */
public class OW0140REFDisplayDialog extends TDialog {

	/** シリアルUID */
	private static final long serialVersionUID = 8943347501807346081L;

	/** コントロールクラス */
	private OW0140REFDisplayDialogCtrl ctrl;

	/** 確定されたかどうか */
	boolean isSettle = false;

	/** スプレッドシートDataSource */
	JCVectorDataSource ds;

	/**
	 * コンストラクタ
	 * 
	 * @param parent
	 * @param modal
	 * @param ctrl コントロールクラス
	 */
	public OW0140REFDisplayDialog(Dialog parent, boolean modal, OW0140REFDisplayDialogCtrl ctrl) {
		super(parent, modal);
		this.ctrl = ctrl;

		setLangMessageID("C02006");
		initComponents();

		super.initDialog();

	}

	/**
	 * フレームを返す
	 */
	public Frame getParentFrame() {
		return super.getParentFrame();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
	 * content of this method is always regenerated by the Form Editor.
	 */
	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		pnlDetial = new TPanel();
		pnlJournal = new TPanel();
		ssJournal = new TTable();
		pnlText = new TPanel();
		txtCode = new TTextField();
		txtNameForSearch = new TTextField();
		pnlButton = new TPanel();
		btnSearch = new TButton();
		btnSettle = new TButton();
		btnCancel = new TButton();

		setResizable(false);

		setLayout(new GridBagLayout());

		pnlDetial.setLayout(new GridBagLayout());

		pnlDetial.setMaximumSize(new Dimension(530, 380));
		pnlDetial.setMinimumSize(new Dimension(530, 380));
		pnlDetial.setPreferredSize(new Dimension(530, 380));
		pnlJournal.setLayout(new javax.swing.BoxLayout(pnlJournal, BoxLayout.X_AXIS));

		pnlJournal.setMaximumSize(new Dimension(530, 300));
		pnlJournal.setMinimumSize(new Dimension(530, 300));
		pnlJournal.setPreferredSize(new Dimension(530, 300));
		ssJournal.setTabControlNo(7);
		ssJournal.setSort(true);
		ssJournal.setEnterToButton(true);
		pnlJournal.add(ssJournal);

		pnlDetial.add(pnlJournal, new GridBagConstraints());

		pnlText.setLayout(new GridBagLayout());

		pnlText.setMaximumSize(new Dimension(530, 30));
		pnlText.setMinimumSize(new Dimension(530, 30));
		pnlText.setPreferredSize(new Dimension(530, 30));
		txtCode.setMaximumSize(new Dimension(129, 20));
		txtCode.setMinimumSize(new Dimension(129, 20));
		txtCode.setPreferredSize(new Dimension(129, 20));
		txtCode.setMaxLength(10);
		txtCode.setTabControlNo(1);
		txtCode.setImeMode(false);
		txtCode.addKeyListener(new KeyAdapter() {

			public void keyPressed(KeyEvent e) {
				if (e.getKeyCode() == KeyEvent.VK_ENTER) {

					if (!txtCode.isFocusOwner() || !txtCode.isEditable()) {
						return;
					}
					setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
					ctrl.condition();
					setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));

				}
			}
		});
		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		gridBagConstraints.insets = new Insets(0, 40, 0, 0);
		pnlText.add(txtCode, gridBagConstraints);

		txtNameForSearch.setMaximumSize(new Dimension(359, 20));
		txtNameForSearch.setMinimumSize(new Dimension(359, 20));
		txtNameForSearch.setPreferredSize(new Dimension(359, 20));
		txtNameForSearch.setTabControlNo(3);
		txtNameForSearch.setMaxLength(40);
		txtNameForSearch.setProhibitionWords("％", "＿");
		txtNameForSearch.addKeyListener(new KeyAdapter() {

			public void keyPressed(KeyEvent e) {
				if (e.getKeyCode() == KeyEvent.VK_ENTER) {

					if (!txtNameForSearch.isFocusOwner() || !txtNameForSearch.isEditable()) {
						return;
					}
					setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
					ctrl.condition();
					setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));

				}
			}
		});
		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.insets = new Insets(0, 2, 0, 0);
		pnlText.add(txtNameForSearch, gridBagConstraints);

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		pnlDetial.add(pnlText, gridBagConstraints);

		pnlButton.setLayout(new GridBagLayout());

		pnlButton.setMaximumSize(new Dimension(475, 35));
		pnlButton.setMinimumSize(new Dimension(475, 35));
		pnlButton.setPreferredSize(new Dimension(475, 35));
		btnSearch.setLangMessageID("C00155");
		btnSearch.setShortcutKey(KeyEvent.VK_F2);
		btnSearch.setMaximumSize(new Dimension(110, 25));
		btnSearch.setMinimumSize(new Dimension(110, 25));
		btnSearch.setPreferredSize(new Dimension(110, 25));
		btnSearch.setTabControlNo(4);
		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.insets = new Insets(5, 10, 0, 0);
		pnlButton.add(btnSearch, gridBagConstraints);
		btnSearch.addActionListener(new ActionListener() {

			public void actionPerformed(ActionEvent evt) {
				btnSearchActionPerformed();
			}
		});

		btnSettle.setLangMessageID("C01019");
		btnSettle.setShortcutKey(KeyEvent.VK_F8);
		btnSettle.setMaximumSize(new Dimension(110, 25));
		btnSettle.setMinimumSize(new Dimension(110, 25));
		btnSettle.setPreferredSize(new Dimension(110, 25));
		btnSettle.setTabControlNo(5);
		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.insets = new Insets(5, 10, 0, 0);
		pnlButton.add(btnSettle, gridBagConstraints);
		btnSettle.addActionListener(new ActionListener() {

			public void actionPerformed(ActionEvent evt) {
				btnSettleActionPerformed();
			}
		});

		btnCancel.setLangMessageID("C00405");
		btnCancel.setShortcutKey(KeyEvent.VK_F12);
		btnCancel.setMaximumSize(new Dimension(110, 25));
		btnCancel.setMinimumSize(new Dimension(110, 25));
		btnCancel.setPreferredSize(new Dimension(110, 25));
		btnCancel.setTabControlNo(6);
		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.insets = new Insets(5, 10, 0, 0);
		pnlButton.add(btnCancel, gridBagConstraints);
		btnCancel.addActionListener(new ActionListener() {

			public void actionPerformed(ActionEvent evt) {
				btnCancelActionPerformed();
			}
		});

		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 2;
		pnlDetial.add(pnlButton, gridBagConstraints);

		add(pnlDetial, new GridBagConstraints());

		// SS
		String[] clabel = new String[] { "C00596", "C00686" };

		// セル幅
		ssJournal.setCharWidth(0, 10);
		ssJournal.setCharWidth(1, 34);

		// スプレッドイベントの初期化
		ssJournal.addSpreadSheetSelectChange(btnSettle);

		// SSデータの構築
		ds = new JCVectorDataSource();
		ds.setNumColumns(2);
		ds.setNumRows(0);
		// 列、行表題のスタイル設定
		int[] columnWidths = new int[] { 10, 34 };
		ssJournal.initSpreadSheet(clabel, columnWidths);

		ssJournal.setDataSource(ds);

	}

	/**
	 * 確定ボタン押下の処理
	 */
	private void btnSettleActionPerformed() {
		isSettle = true;
		ctrl.disposeDialog();
	}

	/**
	 * キャンセルボタン押下の処理
	 */
	private void btnCancelActionPerformed() {
		isSettle = false;
		ctrl.disposeDialog();
	}

	/**
	 * 検索ボタン押下の処理
	 */
	private void btnSearchActionPerformed() {
		ctrl.condition();
	}

	TButton btnCancel;

	TButton btnSearch;

	TButton btnSettle;

	private TPanel pnlButton;

	private TPanel pnlDetial;

	private TPanel pnlJournal;

	private TPanel pnlText;

	TTable ssJournal;

	TTextField txtCode;

	TTextField txtNameForSearch;
}
