SELECT
  KAI_CODE,
  ZAN_TRI_CODE,
  ZAN_SEI_DEN_DATE,
  ZAN_SEI_DEN_NO,
  ZAN_SEI_GYO_NO,
  ZAN_SEI_NO,
  ZAN_KMK_CODE,
  ZAN_HKM_CODE,
  ZAN_UKM_CODE,
  ZAN_AR_DATE,
  ZAN_CUR_CODE,
  ZAN_CUR_RATE,
  ZAN_DEP_CODE,
  SUM(CASE WHEN ZAN_SEI_IN_KIN IS NULL THEN 0 ELSE ZAN_SEI_IN_KIN END 
      - CASE WHEN ZAN_KESI_IN_KIN IS NULL THEN 0 ELSE ZAN_KESI_IN_KIN END) NON_KESI_IN_KIN,
  SUM(CASE WHEN ZAN_SEI_KIN IS NULL THEN 0 ELSE ZAN_SEI_KIN END 
      - CASE WHEN ZAN_KESI_KIN IS NULL THEN 0 ELSE ZAN_KESI_KIN END) NON_KESI_KIN,
  SUM(CASE WHEN ZAN_SEI_IN_KIN IS NULL THEN 0 ELSE ZAN_SEI_IN_KIN END ) SEI_IN_KIN,
  SUM(CASE WHEN ZAN_SEI_KIN IS NULL THEN 0 ELSE ZAN_SEI_KIN END ) SEI_KIN,
  SUM(CASE WHEN ZAN_KESI_IN_KIN IS NULL THEN 0 ELSE ZAN_KESI_IN_KIN END) KESI_IN_KIN,
  SUM(CASE WHEN ZAN_KESI_KIN IS NULL THEN 0 ELSE ZAN_KESI_KIN END) KESI_KIN
FROM
  AR_ZAN
WHERE KAI_CODE = /*param.companyCode*/
  AND CASE WHEN ZAN_SOUSAI_FLG IS null THEN 0
           WHEN ZAN_DATA_KBN = '31' THEN ZAN_SOUSAI_FLG
           ELSE ZAN_SOUSAI_FLG
      END <> 1
  AND ZAN_NYU_UTK_NO IS null
  AND ZAN_SEI_DEN_NO IN /*param.slipNoList*/()  -- ì`ï[î‘çÜ
  
  /*IF param.notIncledEraseSlipNo != null && !"".equals(param.notIncledEraseSlipNo) */
    AND (ZAN_KESI_DEN_NO IS null OR ZAN_KESI_DEN_NO <> /*param.notIncledEraseSlipNo*/)
  /*END*/

GROUP BY
  KAI_CODE,
  ZAN_TRI_CODE,
  ZAN_SEI_DEN_DATE,
  ZAN_SEI_DEN_NO,
  ZAN_SEI_GYO_NO,
  ZAN_SEI_NO,
  ZAN_KMK_CODE,
  ZAN_HKM_CODE,
  ZAN_UKM_CODE,
  ZAN_AR_DATE,
  ZAN_CUR_CODE,
  ZAN_CUR_RATE,
  ZAN_DEP_CODE
HAVING
  SUM(ZAN_SEI_KIN) <> SUM(CASE WHEN ZAN_KESI_KIN IS NULL THEN 0 ELSE ZAN_KESI_KIN END)