SELECT 
    KJL.KJL_LVL         AS KJL_LVL,
    KJL.KJL_UP_DEP_CODE AS KJL_UP_DEP_CODE,
    UBM.DEP_NAME_S      AS KJL_UP_DEP_NAME_S,
    KJL.KJL_DEP_CODE    AS KJL_DEP_CODE,
    DBM.DEP_NAME_S      AS KJL_DEP_NAME_S
FROM
    KJL_MST KJL
      LEFT OUTER JOIN BMN_MST UBM ON KJL.KAI_CODE = UBM.KAI_CODE AND KJL.KJL_UP_DEP_CODE = UBM.DEP_CODE
      LEFT OUTER JOIN BMN_MST DBM ON KJL.KAI_CODE = DBM.KAI_CODE AND  KJL.KJL_DEP_CODE = DBM.DEP_CODE
WHERE
    KJL.KAI_CODE     = /*kaiCode*/ AND
    KJL.KJL_USR_ID   = /*usrId*/   AND
    KJL.KJL_DPK_SSK  = /*dpkSsk*/  AND
    KJL.KJL_KMT_CODE = /*kmtCode*/